### ISSUE TITLE
Missing Data Files?

### ISSUE THREAD

**Issue by stevedough123** [dmcable/RCTD#2] opened 2020-06-19 09:44 UTC
I'm currently attempting to run RCTD on the cerebellum data given in the Robust decomposition of cell type mixtures in spatial transcriptomics. However, I can't find the dge.csv, cell_type_dict.csv, and meta_data.csv files that are needed for the single-cell reference section. In the data on the Single Cell portal, there an .RDS file which contains the information of the .csv files. How do I input this into RCTD?

If I try to use the terminal to run the pipeline, I get this error: 
homes-iMac:RCTD_base home$ Rscript R_scripts/callDoublets.R 1 
Error: unexpected symbol in "Script started"
Execution halted

**Comment by dmcable** [comment] 2020-06-19 21:25
Hi Steve, all the data used to run RCTD is here [https://singlecell.broadinstitute.org/single_cell/study/SCP948/robust-decomposition-of-cell-type-mixtures-in-spatial-transcriptomics](url). Actually, the file 'scRefSubsampled1000_cerebellum_singlenucleus.RDS' contains the preprocessed cerebellum reference as a Seurat object. This allows you to skip the step of creating the .csv files. If you are following the instructions here 'https://github.com/dmcable/RCTD,' then you can proceed to step 2 and make sure to set 'reffolder', and 'reffile' to reference this RDS file. 

For the error that you describe, it is because you need to get steps 1-2 working before running the pipeline. I recommend following along with the ‘spatial-transcriptomics’ vignette to test if it is working correctly.

**Comment by stevedough123** [comment] 2020-06-20 03:44
Thanks. I also get this error when I'm running the code in R studio (image below). I'm assuming it's because 'reference' is suppose to contain the Seurat object from the preprocessing step. But since I'm skipping that step like you mentioned, the next part wouldn't recognize any Seurat object. Do you have any idea how to bypass this step in 
![image](https://user-images.githubusercontent.com/52977783/85190345-5e81d300-b26c-11ea-8b59-799652679c95.png)

I'm also getting the following issues when I run the subsequent chunks of code in the Vignette:
![image](https://user-images.githubusercontent.com/52977783/85190401-01d2e800-b26d-11ea-9087-c28cae74218c.png)
![image](https://user-images.githubusercontent.com/52977783/85190479-b40aaf80-b26d-11ea-8a0e-902eadfdee72.png)
![image](https://user-images.githubusercontent.com/52977783/85190456-86256b00-b26d-11ea-9765-73c24acaf44f.png)

**Comment by dmcable** [comment] 2020-06-20 12:15
I see, so the first thing I would recommend is to make sure that you can successfully run the spatial-transcriptomics Vignette, by following the instructions here [github.com/dmcable/RCTD](url). This should run without errors in 5-10 minutes and should be instructive for how the pipeline works.

To fix your error of 'reference not found', you can load in the Seurat reference as:
`reference <- readRDS('location of reference file.RDS')` 

Next, if you also haven't yet created the slide-seq puck .RDS file, you can follow the instructions in the 'Slide-seq data' section of the spatial-transcriptomics Vignette.

Your goal should be to make sure the following line of code initializes RCTD successfully:
`iv <- init_RCTD(gene_list_reg = F, get_proportions = F, load_info=F)` 
In order for this to work, you need to have the following files on your computer:
1) The single nucleus reference .RDS file
2) The slide-seq puck .RDS file. 
3) The `config.yml` file, which contains SpatialRNAfolder, puckrds, reffolder, and reffile fields are updated to contain the file locations of (1) and (2). 

After you are able to successfully run the `init_RCTD` function, you have the option of following the 'Running RCTD from Command Line' ([github.com/dmcable/RCTD](url)) to run the pipeline in a streamlined fashion. The first step would be platform effect normalization:
`Rscript R_scripts/fitBulk.R`. My recommendation for the spatial-transcriptomics vignette dataset would be to run each line in the vignette to see how it works, but then for the cerebellum dataset, you could just run from command line after getting `init_RCTD` working.

The error you received for `iv <- init_RCTD(load_info_renorm = T)` is because you first need to successfully run the previous parts of the pipeline. In particular, the 'Platform Effect Normalization' step will create the renormalized cell type profiles. Likewise with the subsequent lines -- they depend on successful execution of the previous lines. So, your first step is to get the `iv <- init_RCTD(gene_list_reg = F, get_proportions = F, load_info=F)` line working.

**Comment by stevedough123** [comment] 2020-06-21 07:47
Thanks again for your help. I think I've almost got it running. 

After successfully running ### Running Platform Effect Normalization, the code runs into an error at the following step:

![image](https://user-images.githubusercontent.com/52977783/85219442-9cf4bc00-b358-11ea-8e6d-caa31b9c9794.png)

For a more detailed description, here is what it says in the R studio console:

![image](https://user-images.githubusercontent.com/52977783/85219462-c281c580-b358-11ea-8e45-42d88b801b3f.png)

**Comment by dmcable** [comment] 2020-06-21 11:49
Ok, this is an issue with the parallelization, and unfortunately these kinds of errors can be tricky and opaque, but I am definitely interested in figuring out why this is occurring. Is this on the Vignette dataset or the Cerebellum dataset? I'm not exactly sure, but here are a few ideas:

1) Make sure the required packages are installed: 
```
library(doParallel)
library(parallel)
library(foreach)
```
This should hopefully not return any errors. 

2) Next, can you execute the following code without error:

```
cl <- parallel::makeCluster(4,outfile="")
doParallel::registerDoParallel(cl)
parallel::stopCluster(cl)
```

If so, then it is a problem with the `foreach` loop.

3) It could be a memory issue. How many GB of RAM does your computer have? You could try closing other memory intensive applications. You might be using a lot of memory in your R session. Can you please show the output of `gc()`?

4) Could you please provide the output of `sessionInfo()`?

To answer the second question, there were two different Cerebellum annotated references used in our study, a single-nucleus RNA-seq dataset (scRefSubsampled1000_cerebellum_singlenucleus.RDS.zip) and a single-cell RNA-seq dataset (1000cellsSubsampled_cerebellum_singlecell.RDS.zip). The single-nucleus dataset was used as training data for the Slide-seq Cerebellum, so I believe you should use that one. The single-cell dataset was used to generate a "simulated slide-seq" dataset in order to benchmark the performance of RCTD.

**Comment by stevedough123** [comment] 2020-06-21 19:05
Okay thanks, I'll see if those work.

On another note, I also tried running RCTD in my terminal, but I still got this error
![image](https://user-images.githubusercontent.com/52977783/85232881-8a5d9f80-b3b7-11ea-8ba7-a6e5dfee9bc7.png)

**Comment by dmcable** [comment] 2020-06-21 19:44
Great, for scRNA-seq vs snRNA-seq, RCTD was designed to work for either platform. In fact, for the hippocampus Slide-seq dataset, we tested it on single cell. For the cerebellum Slide-seq, we chose the single-nucleus dataset because we thought it was higher in quality, but there is no inherent reason that we did not use the single-cell for cerebellum. 

I can't see the command that you used in terminal, but I believe it was 
`Rscript R_scripts/chooseSigma.R`. 
If so, then it seems like you successfully ran the part of RCTD that you were previously experiencing errors. I believe that you may be able to fix the issue by clearing your R environment and restarting Rstudio. Otherwise, since you were able to run it as a terminal command, that is perfectly fine.

Now that we have identified the error, after you restart RStudio, you can test for the error as:
```
library(parallel)
cl <- parallel::makeCluster(4,outfile="")
```

As for your error you are experiencing with `Rscript R_scripts/callDoublets.R 1`, I am not sure exactly the issue, but it should be relatively easy to fix. Do you have any more information? You could try opening up Rstudio and running the first few lines of `callDoublets.R` to see if it works.

**Comment by stevedough123** [comment] 2020-06-21 19:49
So just to clarify, if I run the code chunks in R Studio in the spatial-transcriptomic.Rmd file, it won't work, but running it in my terminal will work.

Also, you are correct, I did run the chooseSigma.R file before the callDoublets.R file. Strangely, this is what shows up when I open the file:
![image](https://user-images.githubusercontent.com/52977783/85233750-a06e5e80-b3bd-11ea-8b21-02800c16b96e.png)

**Comment by dmcable** [comment] 2020-06-21 20:01
Ok, sorry its not working in RStudio, but it's completely fine going forward to just run it in terminal, since the pipeline is fully encapsulated in the scripts. 

Interesting, it looks like the callDoublets.R file somehow got overwritten. You can download it again from the RCTD github, or for convenience I have attached the file here (to be unzipped first): [callDoublets.R.zip](https://github.com/dmcable/RCTD/files/4810184/callDoublets.R.zip).

**Comment by stevedough123** [comment] 2020-06-21 20:16
Thanks. When I'm running the callDoublets file, do I run it 20 times, and increase the number from 1-20 each time I run it on a new line?

**Comment by stevedough123** [comment] 2020-06-21 22:37
Just to make sure, is there any issue with the way the script is running in my terminal right now?

![image](https://user-images.githubusercontent.com/52977783/85236692-0adec900-b3d5-11ea-8e05-7970d106dafe.png)

**Comment by dmcable** [comment] 2020-06-21 23:13
Hey Steve,

Yes that looks good, though I should point out that it says "number of cell types used: 11". Which scRNA-seq reference are you using? I believe the cerebellum snRNA-seq dataset has 19 cell types. You are correct about how to run the callDoublets.R script 20 times. It would be tedious to enter in each of the 20 jobs by hand. In the next version of RCTD, we have made it approximately 30 times faster, and as a result, we will remove this annoying step of splitting the data into multiple chunks. For now, you have the following options:

1. The splitting into multiple chunks is really only useful (and designed) for people who are using a computer cluster where they can run multiple jobs at once. Since you are running on a standard computer, you could avoid this entirely by setting the `n_puck_folds` variable to 1 (instead of 20 by default) in the config.yml file. However, if you change `n_puck_folds`, be warned that you do need to go back and run the scripts from the start.
2. You could write a (bash) script that will loop over 1 to 20 and run the `callDoublets.R` script for each value.

**Comment by stevedough123** [comment] 2020-06-22 09:44
Hi,

I have 11 cell types because I'm using the 1000cellsSubsampled_cerebellum_singlecell.RDS.zip file, not the single nucleus one.

**Comment by dmcable** [comment] 2020-06-22 11:20
Got it, in that case everything checks out!

**Comment by stevedough123** [comment] 2020-06-22 22:19
Thanks. So after I'm done running `callDoublets.R` 20 times, I just run the following line and the output is downloaded onto my Mac?

`Rscript R_scripts/gather_results.R`

Also, what exactly is RCTD outputting? Is there any further analysis or scripts I have to run in order to get figures and tables afterward? 

Thanks for your help!

**Comment by stevedough123** [comment] 2020-06-23 10:09
I just tried running on the larger single nucleus dataset, but I'm getting this issue:

![image](https://user-images.githubusercontent.com/52977783/85391038-84bea180-b4fe-11ea-9fc1-ae9c3ed5923f.png)

**Comment by dmcable** [comment] 2020-06-23 13:38
Yes, your R session ran out of memory, so you should clear all the objects in your R environment and reset your R session.

You are correct about running `callDoublets.R` at the end. It will aggregate all of the data into the `results` object, and then it will generate several plots (saved in the 'results' folder). If you would like to make different plots/tables than what it makes, you can select the `results` object and process and/or export it.

**Comment by stevedough123** [comment] 2020-06-25 10:50
Thanks.

Following up on one of my earlier messages, I wanted to see if there were any numerical data values associated with the results? Mainly, I wanted to see if there was a way to compare your results to the "ground truth" or test for certain factors such as accuracy and precision.

**Comment by dmcable** [comment] 2020-06-25 11:53
Hello, that's a good question, and unfortunately ground truth cell type information cannot be collected for Slide-seq datasets. As a result, we develop several strategies in our paper to validate RCTD:

1) Validation of RCTD on "ground truth" simulated Slide-seq datasets of computational mixtures of known single cells. This is done cross platform (single-nucleus to single-cell) to incorporate the challenging existence of platform effects. Given a ground truth dataset, we can calculate any performance statistic we desire, and we demonstrate several in the paper (single cell type identification accuracy, doublet detection accuracy, doublet cell type identification accuracy, cell type proportion estimation). 

2) Of course it is still important to validate Slide-seq data directly. We employ the following strategies in the paper: 
a. validation of spatial localization of cell types using prior biological knowledge of spatial organization in the cerebellum and hippocampus. 
b. comparing RCTD cell type predictions to localization of cell type marker genes or metagenes (i.e. summed expression of multiple marker genes) 
c. Making sure that "singlets" have only marker genes from a single cell type, whereas "doublets" have marker genes from two cell types. (We demonstrated this in the case of Bergmann / Purkinje calls). 
d. Making sure that doublets only occur between pairs of cell types that are known to co-localize spatially.

Of course, we are always open for better ideas on how to validate RCTD. Hope this helps!

**Comment by stevedough123** [comment] 2020-06-26 20:35
Sure, thanks for the information. For new datasets, is there a way to obtain these validation results?

**Comment by dmcable** [comment] 2020-06-26 23:04
Sure, I have written instructions for reproducing all of the validation / figures in the paper here https://github.com/dmcable/RCTD/tree/dev/AnalysisPaper. I recommend clicking the links under 'Generating Main Figures' to see the R code that was used to generate each figure. Hope this helps!

**Comment by dmcable** [comment] 2020-06-26 23:18
Several validation plots are automatically output by the `gather_results.R` script. If you want to compare to specific marker genes, you can plot those individual genes and compare. If you have a more specific example, I'd be happy to help.

Future datasets you may have will work fine if they are put into the file format that RCTD accepts (counts matrix and coordinates matrix).

**Comment by stevedough123** [comment] 2020-06-29 17:55
Thanks. I'm trying to run a different dataset through your pipeline, but we created a psuedo-Visium dataset that we will use as the "ground truth."

**Comment by dmcable** [comment] 2020-06-30 18:12
Cool - could you please explain what you mean by pseudo-Visium dataset?

Yes, those are all of the plots that are generated by default. Do you have a particular plot you are looking for?

**Comment by stevedough123** [comment] 2020-07-03 10:41
I'm mainly looking to represent the detection of spatially variable genes within specific cell types (imputation of genetic information). For example, I want to recreate Figure 6 (particularly Figure 6D) and possibly with different genes from my own dataset. In other words, I'm mostly looking to better understand and recreate the sections in your paper "RCTD enables detection of spatially variable genes within cell type" and "Expected cell type-specific gene expression", since these data are what I'm attempting to look at.

In this dataset that I'm using, however, I noticed that the files are different than the input required for this pipeline. Is it possible to transform the data, and if so, how do I go about inputing it into the pipeline? 

Here are the files from my dataset with the different file names (these are the only 4 files):

![image](https://user-images.githubusercontent.com/52977783/86460896-091eda80-bcde-11ea-8734-24674a5658b3.png)
![image](https://user-images.githubusercontent.com/52977783/86458850-c4457480-bcda-11ea-9f81-42e327a50dc1.png)
![image](https://user-images.githubusercontent.com/52977783/86460916-1045e880-bcde-11ea-942d-5d89a5001ec9.png)

For the above .csv file, do I need to get rid of the histology column?

![image](https://user-images.githubusercontent.com/52977783/86460847-f4424700-bcdd-11ea-9d70-280e5464c4e2.png)

I don't think the annotations are important, they are just an extra file.

Specifically, I'm wondering about the `## Single-Cell Reference` section on the Vingenette. It asks for `meta_data.csv`, `cell_type_dict.csv`, and `dge.csv` or an RDS Seurat object with this data. So given the dataset I'm currently using, how would I run and get past these initial steps? Also, which of my files is for the `MappedDGEForR.csv`part of the input?

Thanks.

**Comment by stevedough123** [comment] 2020-07-07 19:21
Also, I'm assuming in order to change Figure 6 I would just go into the code and alter the gene name and cell types?

**Comment by stevedough123** [comment] 2020-07-10 11:09
So I ran RCTD on a new dataset of mine, and I'm getting the following errors:

![image](https://user-images.githubusercontent.com/52977783/87148334-12babc00-c263-11ea-8567-8c2fa6372ed8.png)

![image](https://user-images.githubusercontent.com/52977783/87148375-2108d800-c263-11ea-8b69-cde90aab2384.png)

Is there something wrong with my data, or should I change parts of the code?

**Comment by dmcable** [comment] 2020-07-16 18:29
Hi Steve, I encourage you to check out the new version of RCTD, which was just released yesterday! It is 30 times faster and significantly easier to use. The input procedure, however, has not changed.

I think your issues are because the data needs to be put in different format. You can find some guidelines about data format here: https://raw.githack.com/dmcable/RCTD/dev/vignettes/spatial-transcriptomics.html.

For the spatial transcriptomics data:
Next, put the SpatialRNA data (in this case Slide-seq) in your ‘data/SpatialRNA’ directory (here ‘data/SpatialRNA/Vignette’). This needs to contain:
1. BeadLocationsForR.csv: a CSV file (with 3 columns, with headers “barcodes”, “xcoord”, and “ycoord”) containing the spatial locations of the pixels.
--For this file, you are close (ST-lymphnodes-coordinates.txt), you just need to get rid of the histology column (in excel right click then delete column), and rename the column names.
2. MappedDGEForR.csv: a DGE (gene counts by barcodes) CSV file. Represents raw counts at each pixel.
--You are also very close (ST_lympnodes_geneExpression.tsv). You should just be able to do file save as csv. All you need to do is change it from a tsv to csv file.

For the scRNA reference, here are the instructions. If you have a particular question on how to create one of the files, I can provide more specific help. A good approach for you would be to open the files in the ‘data/Reference/Vignette’ sample folder so you can see how they should be formatted.

Create a folder in ‘data/Reference’ e.g. ‘data/Reference/Vignette’ containing the following three files:
1. meta_data.csv: a CSV file (with 3 columns, with headers “barcode”, “cluster”, and “nUMI”) containing the numeric cluster assignment for each cell.
2. cell_type_dict.csv: a CSV file (with 2 columns, with headers “Cluster” and “Name”) containing the mapping between numeric cluster ID and cluster name. If you want a cluster to be filtered out of the single cell reference, you can leave the cluster name blank. The cell types must not contain the character ‘/’ or ‘-’.
3. dge.csv: a Digital Gene Expression (DGE) (barcodes by gene counts) CSV file in the standard 10x format.
We use the dgeToSeurat function:

**Comment by stevedough123** [comment] 2020-07-16 19:59
Thanks for your help. I reformatted the files to match the 5 .csv files that you used for input for RCTD, as shown below. 

MappedDGEForR:
![image](https://user-images.githubusercontent.com/52977783/87715552-6137f100-c762-11ea-863f-e76e6706fbdf.png)

BeadLocationsForR:
![image](https://user-images.githubusercontent.com/52977783/87715652-875d9100-c762-11ea-9294-d070a5e58a6b.png)

cell_type_dict
![image](https://user-images.githubusercontent.com/52977783/87715675-8f1d3580-c762-11ea-86d3-b579d0610c54.png)

meta_data:
![image](https://user-images.githubusercontent.com/52977783/87715591-701ea380-c762-11ea-8326-13b7bb607c9c.png)

dge:
![image](https://user-images.githubusercontent.com/52977783/87715924-e7543780-c762-11ea-8943-ddbb8f15206b.png)

However, when I try to run RCTD on this pipeline, I still get the following errors: 
![image](https://user-images.githubusercontent.com/52977783/87716612-eff93d80-c763-11ea-8f70-8fdfd7a3eefc.png)
![image](https://user-images.githubusercontent.com/52977783/87716738-259e2680-c764-11ea-8923-2d9182679a19.png)

Also, for the errors I stated in my previous message, that was after I correctly reformatted the data as you mentioned.

**Comment by stevedough123** [comment] 2020-07-19 11:15
When trying to read in the dge.csv, meta_data.csv, and cell_type_dict.csv files, I also get the following error:

![image](https://user-images.githubusercontent.com/52977783/87873357-e5ae8d80-c975-11ea-8d2a-fc02d7f81e0e.png)

Also, when I try to install the new version of RCTD, the R console doesn't give me a chance to give a number response to the following prompt:
![image](https://user-images.githubusercontent.com/52977783/87873397-505fc900-c976-11ea-88ac-4bb65373d80b.png)

And, I end up with the error:
![image](https://user-images.githubusercontent.com/52977783/87873419-6b323d80-c976-11ea-9dd5-6c5823226c14.png)

**Comment by stevedough123** [comment] 2020-07-22 02:55
I noticed that your instructions to install the code on GitHub is not
working properly (the devtools section of README). Could you help me look
into this?

**Comment by dmcable** [comment] 2020-07-22 10:25
Sure, can you please post what happens when you try to execute the installation command?

**Comment by stevedough123** [comment] 2020-07-22 11:08
Thanks for your quick response.

Here's what happens when I try to run the installation command line in
terminal:
[image: image.png]

 And then when I try to install the new version of RCTD in Rstudio, I still
get an error (also, if this is relevant, the R console doesn't give me a
chance to give a number response to the following prompt):
[image: image.png]
[image: image.png]

Also, I'm not sure if you saw my previous message on GitHub, but it seems
that I'm getting a similar error message in the preprocessing step when I
attempt to run the older version of RCTD on my dataset. When trying to read
in the dge.csv, meta_data.csv, and cell_type_dict.csv files, I get the
following error:
[image: image.png]

I would greatly appreciate your help in these issues.

Lastly, as an alternative, maybe I could send you the dataset and you could
take a look at it or attempt to run RCTD on it? Sorry if this seems
unexpected, but I've been working on this for quite some time and am trying
to move along. However, I'm sure you're busy and may not have the time to
do this, but if it's possible, we could communicate over email (you can
reach me at sdou1@stanford.edu).

**Comment by stevedough123** [comment] 2020-07-25 08:47
Thanks for your help, I didn't see your previous message, apologies for sending the same message. 

So I fixed the row.names issues, but now I'm running into a few more issues that I brought up in a new Issue.

**Comment by stevedough123** [comment] 2020-07-25 09:35
Thanks for your help, I didn't see your previous message, apologies for sending the same message.

**Comment by stevedough123** [comment] 2020-07-27 08:00
So I was able to get the RCTD_plots produced. Is it possible to get the assignment scores from the cell types? Specifically, is it possible to export the locations of each cell type in a csv or RDS file (I'm assuming these should be the input for the plots that are output from RCTD)? That way I can compare the results with other methods.

**Comment by stevedough123** [comment] 2020-07-29 09:43
Also, is there a way to increase the size of the beads/pixels and make it so that there is less white space in the plots? Could I change the coloring of the beads as well? Lastly, is there a way to rotate or flip the plots, which I want to do in order to compare RCTD to results from different methods?

**Comment by lulizou** [comment] 2020-07-29 12:01
Hi Steve,
The assignment scores can be found in the results object in `results$results_df`. The current plotting capabilities aren't very flexible, but all of the information needed to create the plots is in the `myRCTD` project, so the easiest way would be to look at building/customizing the plots you want using the `ggplot2` package, which is what RCTD uses.
Best,
Luli

**Comment by dmcable** [comment] 2020-07-29 15:18
Hi Steve,

Regarding your previous question, I unfortunately wouldn't have time to personally run RCTD on your dataset, but I am glad to see you got everything working!

Dylan

**Closed by dmcable** 2020-07-29 15:18 UTC
